const GET_DATA_SAGA = 'GET_DATA_SAGA';
const SET_DATA = 'SET_DATA';
const USER_ANSWERS = 'USER_ANSWERS';
const CORRECT_ANSWERS = 'CORRECT_ANSWERS';
const COUNT_RESULT = 'COUNT_RESULT';
const START_PAGE = 'START_PAGE';
const CURRENT_QUESTION_ID = 'CURRENT_QUESTION_ID';

export {  //eslint-disable-line
  GET_DATA_SAGA,
  SET_DATA,
  USER_ANSWERS,
  CORRECT_ANSWERS,
  COUNT_RESULT,
  START_PAGE,
  CURRENT_QUESTION_ID,
};
